#' @import rlang
#' @importFrom utils head
#' @importFrom purrr map map_chr discard map2_dfr map_dfr map2 map_lgl accumulate
#' @import dplyr
#' @import tibble
#' @rawNamespace import(glue, except = c(collapse))
#' @importFrom tidyr unnest nest
#' @rawNamespace import(lubridate, except = c(intersect, union, setdiff))
#' @importFrom stats na.omit
#' @importFrom utils read.csv
NULL

globalVariables(".")
globalVariables("ABBREV_1_Text_de")
globalVariables("cAbbreviation")
globalVariables("cAbbreviation.x")
globalVariables("ct_short")
globalVariables("ct_name")
globalVariables("desired")
globalVariables("dHistId")
globalVariables("from")
globalVariables("Identifier")
globalVariables("Level")
globalVariables("mAbolitionDate")
globalVariables("mAbolitionMode")
globalVariables("mAdmissionDate")
globalVariables("mAdmissionMode")
globalVariables("mAdmissionMode.x")
globalVariables("mDateOfChange.y")
globalVariables("mHistId")
globalVariables("mHistId.x")
globalVariables("mHistId.y")
globalVariables("mId")
globalVariables("mId.x")
globalVariables("mId.x.x")
globalVariables("mId.y")
globalVariables("mId.y.x")
globalVariables("mMutationDate")
globalVariables("mMutationDate.x")
globalVariables("mMutationDate.y")
globalVariables("mMutationId")
globalVariables("mMutationNumber")
globalVariables("mMutationNumber.x")
globalVariables("mShortName")
globalVariables("mShortName.x")
globalVariables("mShortName.x.x")
globalVariables("mShortName.y")
globalVariables("mShortName.y.x")
globalVariables("mun_id")
globalVariables("mun_id_x")
globalVariables("mun_id_y")
globalVariables("mun_name")
globalVariables("mutation_year")
globalVariables("Name_de")
globalVariables("Parent")
globalVariables("rename_date")
globalVariables("short_name")
globalVariables("short_name_x")
globalVariables("short_name_y")
globalVariables("target_year")
globalVariables("value")
globalVariables("variable")
globalVariables("year_from")
globalVariables("year_to")
